#
# Install Parallel NetCDF Fortran and its dependencies
#

ARG TOOLCHAIN
FROM minimal-toolchain:$TOOLCHAIN

# Install the dependencies
RUN apt-get update \
 && DEBIAN_FRONTEND=noninteractive apt-get --yes install --no-install-recommends \
      tar \
 && rm -rf /var/lib/apt/lists/*

# Define PnetCDF version and installation prefix
ENV PNETCDF_VERSION=1.12.3
ENV PNETCDF_PREFIX=/opt/pnetcdf

# PnetCDF needs this variables (could be set in "minimal" step)
ENV MPICC=mpicc
ENV CXX=icpx

# Download, build, and install PnetCDF
RUN mkdir -p /tmp/pnetcdf_src \
    && wget -qO- https://parallel-netcdf.github.io/Release/pnetcdf-${PNETCDF_VERSION}.tar.gz | tar -xz -C /tmp/pnetcdf_src --strip-components=1 \
    && cd /tmp/pnetcdf_src \
    && ./configure --prefix=${PNETCDF_PREFIX} --disable-shared \
    && make -j \
    && make install \
    &&rm -rf /tmp/pnetcdf_src

# Add PnetCDF library path to the environment
ENV PATH="${PNETCDF_PREFIX}/bin:${PATH}"
ENV LD_LIBRARY_PATH="${PNETCDF_PREFIX}/lib:${LD_LIBRARY_PATH}"
